# Generated by Django 4.0.3 on 2022-03-27 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 27, 19, 16, 38, 19452), editable=False),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='product_slug', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
