# Generated by Django 4.0.3 on 2022-04-10 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_product_created_at_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 10, 15, 36, 49, 722583), editable=False),
        ),
        migrations.DeleteModel(
            name='Cart_Total',
        ),
    ]
